export const SUB_AUA_REGISTRATION = "SUB_AUA_REGISTRATION";

export const SUB_AUA_DAILY_COUNT = "SUB_AUA_DAILY_COUNT";
export const LOADING_ON = "LOADING_ON";
export const LOADING_OFF = "LOADING_OFF";
export const CLEAR_STATE = "CLEAR_STATE";
