export const SUBAUA_APPROVAL = "SUBAUA_APPROVAL";
export const GET_SUBAUA = "GET_SUBAUA";
export const FILE_UPLOAD = "FILE_UPLOAD";
export const SUBAUA_FORM_APPROVED = "SUBAUA_FORM_APPROVED";
export const SUBAUA_DATA = "SUBAUA_DATA";

export const SUBAUA_FORM_DOCUMENTS = "SUBAUA_FORM_DOCUMENTS";
export const ADMIN_DOCUMENT_STATUS = "ADMIN_DOCUMENT_STATUS";

export const SUBAUA_GEN_API = "SUBAUA_GEN_API";

export const SUBAUA_API_KEY = "SUBAUA_API_KEY";



export const ACCOUNT_STATUS = "ACCOUNT_STATUS";



export const LOADING_ON = "LOADING_ON";
export const LOADING_OFF = "LOADING_OFF";
export const CLEAR_STATE = "CLEAR_STATE";
export const ADMIN_ERROR_STATE = "ADMIN_ERROR_STATE";

export const ADMIN_DIALOG_OPEN = "ADMIN_DIALOG_OPEN";
export const ADMIN_DIALOG_CLOSE = "ADMIN_DIALOG_CLOSE";
export const ADMIN_DIALOG_DATA = "ADMIN_DIALOG_DATA";
