export const SUB_AUA_TRACKER = "SUB_AUA_TRACKER";
export const SUB_AUA_SUCCESS_STATUS = "SUB_AUA_SUCCESS_STATUS";

export const SUB_AUA_PAYMENT_DETAILS_NAVIGATE =
  "SUB_AUA_PAYMENT_DETAILS_NAVIGATE";
export const SUB_AUA_CHANGEPASSWORD = "SUB_AUA_CHANGEPASSWORD";
export const SUB_AUA_GET_ALL_NOTIFICATION = "SUB_AUA_GET_ALL_NOTIFICATION";
export const SUB_AUA_TRANSACTIONAL_MODEL_AMOUNT =
  "SUB_AUA_TRANSACTIONAL_MODEL_AMOUNT";

export const SUB_AUA_INVOICE_GENERATOR = "SUB_AUA_INVOICE_GENERATOR";

export const SUB_AUA_LOADING_ON = "SUB_AUA_LOADING_ON";
export const SUB_AUA_LOADING_OFF = "SUB_AUA_LOADING_ON";
export const SUB_AUA_CLEAR_STATE = "SUB_AUA_CLEAR_STATE";
