export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_FORGOT_PASSWORD = "AUTH_FORGOT_PASSWORD";
export const AUTH_CHANGE_PASSWORD = "AUTH_CHANGE_PASSWORD";
export const AUTH_REQUEST_OTP = "AUTH_REQUEST_OTP";
export const AUTH_SEND_OTP = "AUTH_SEND_OTP";
export const AUTH_SUBAUA_CHANGEPASSWORD = "AUTH_SUBAUA_CHANGEPASSWORD";

export const AUTH_LOADING_ON = "AUTH_LOADING_ON";
export const AUTH_LOADING_OFF = "AUTH_LOADING_OFF";
export const EMPTY_AUTH_STATE = "EMPTY_AUTH_STATE";
export const AUTH_ERROR = "AUTH_ERROR";
