export const SUPERADMIN_LOADING_ON = "SUPERADMIN_LOADING_ON";
export const SUPERADMIN_LOADING_OFF = "SUPERADMIN_LOADING_OFF";
export const SUPERADMIN_CLEAR_STATE = "SUPERADMIN_CLEAR_STATE";

export const SUPERADMIN_VIEW_DOCUMENTS = "SUPERADMIN_VIEW_DOCUMENTS";
export const SUPERADMIN_ADD_DOCUMENTS = "SUPERADMIN_ADD_DOCUMENTS";
export const SUPERADMIN_DELETE_DOCUMENTS = "SUPERADMIN_DELETE_DOCUMENTS";
export const SUPERADMIN_UPDATE_DOCUMENTS = "SUPERADMIN_UPDATE_DOCUMENTS";
