export const GET_ALL_SUBAUA_COUNT = "GET_ALL_SUBAUA_COUNT";
export const GET_AUA_TODAY_TRANSACTION_COUNT =
  "GET_AUA_TODAY_TRANSACTION_COUNT";

export const GET_AUA_TOTAL_TRANSACTION_COUNT =
  "GET_AUA_TOTAL_TRANSACTION_COUNT";


export const GET_AUA_TODAY_TOTAL_TRANSACTION_COUNT =
  "GET_AUA_TODAY_TOTAL_TRANSACTION_COUNT";

export const GET_AUA_TODAY_EKYC_TRANSACTION_COUNT =
  "GET_AUA_TODAY_EKYC_TRANSACTION_COUNT";

export const GET_AUA_YEARWISE_COUNT = "GET_AUA_YEARWISE_COUNT";

export const GET_AUA_AUTH_MONTHLY_WISE = "GET_AUA_AUTH_MONTHLY_WISE";
export const GET_AUA_EKYC_MONTHLY_WISE = "GET_AUA_EKYC_MONTHLY_WISE";

export const GET_AUA_AUTH_DONUTCHART_YEARWISE =
  "GET_AUA_AUTH_DONUTCHART_YEARWISE";

export const GET_AUA_EKYC_DONUTCHART_YEARWISE =
  "GET_AUA_EKYC_DONUTCHART_YEARWISE";

export const GET_AUA_AUTH_DONUTCHART_TODAYWISE =
  "GET_AUA_AUTH_DONUTCHART_TODAYWISE";

export const GET_AUA_EKYC_DONUTCHART_TODAYWISE =
  "GET_AUA_EKYC_DONUTCHART_TODAYWISE";

export const GET_AUA_ALLSUBAUA = "GET_AUA_ALLSUBAUA";


export const GET_INVOICE_DETILES = "GET_INVOICE_DETILES";


export const GET_TRANS_INVOICE = "GET_TRANS_INVOICE";

export const INVOICE_EDIT_DETILES = "INVOICE_EDIT_DETILES";

export const INVOICE_PRINT_DETILES = "INVOICE_PRINT_DETILES"

export const PAYMENT_PLANS_VIEW = "PAYMENT_PLANS_VIEW";

export const REPORT_LIST_DASHBOARD = "REPORT_LIST_DASHBOARD";

export const ORGLIST = 'ORGLIST';


export const REPORT_LOADING_ON = "LOADING_ON";
export const REPORT_LOADING_OFF = "REPORT_LOADING_OFF";
export const REPORT_CLEAR_STATE = "REPORT_CLEAR_STATE";
